export {
  getInternalHelperManager,
  helperCapabilities,
  componentCapabilities,
  modifierCapabilities,
  getComponentTemplate,
  getCustomTagFor,
  setModifierManager,
  setHelperManager,
  setInternalHelperManager,
  setComponentManager,
  setComponentTemplate,
  getInternalComponentManager,
  setCustomTagFor,
  setInternalModifierManager,
} from '@glimmer/manager';
