export {
  ALLOW_CYCLES,
  combine,
  createUpdatableTag,
  createTag,
  beginUntrackFrame,
  endUntrackFrame,
  dirtyTag,
  CONSTANT_TAG,
  CURRENT_TAG,
  consumeTag,
  createCache,
  dirtyTagFor,
  getValue,
  tagFor,
  tagMetaFor,
  untrack,
  validateTag,
  valueForTag,
  isTracking,
  updateTag,
  isConst,
  track,
  trackedData,
} from '@glimmer/validator';
export type { Cache, Tag, TagMeta, UpdatableTag, DirtyableTag, Revision } from '@glimmer/validator';
