branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+/

language: node_js
node_js:
  - 6

matrix:
  fast_finish: true

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH="$HOME/.yarn/bin:$PATH"

jobs:
  include:
    - name: Tests
      env:
        - SAUCE_USERNAME=htmlbars-ci
        - SAUCE_ACCESS_KEY=71947947-f373-4e9c-9166-23038df7ddf2

      addons:
        chrome: stable

      before_script:
        - yarn run sauce:connect

      script:
        - yarn run test:ci

      after_script:
        - sleep 10
        - yarn run sauce:disconnect

    - name: Type Tests

      script:
        - yarn run build
        - yarn run test:types

    - name: Linting

      script:
        - yarn run problems
        - yarn run tslint
        - yarn run eslint
