branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+/

language: node_js
node_js:
  - 6

matrix:
  fast_finish: true

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH="$HOME/.yarn/bin:$PATH"

jobs:
  include:
    - name: Tests (Chrome + Node.js)

      addons:
        chrome: stable

      script:
        - yarn test

    - name: Tests (Saucelabs)
      env:
        - SAUCE_USERNAME=htmlbars-ci
        - SAUCE_ACCESS_KEY=71947947-f373-4e9c-9166-23038df7ddf2

      before_script:
        - yarn sauce:connect

      script:
        - yarn test:sauce

      after_script:
        - sleep 10
        - yarn sauce:disconnect

    - name: Type Tests

      script:
        - yarn build
        - yarn test:types

    - name: Linting

      script:
        - yarn problems
        - yarn tslint
        - yarn eslint
