packages:
  - 'bin'
  - '.meta-updater'
  - 'build'
  - 'benchmark/benchmarks/krausest'
  - 'packages/@glimmer/*'
  - 'packages/@glimmer/*/test'
  - 'packages/@glimmer-workspace/*'
  - 'packages/@glimmer-workspace/*/test'
  - 'packages/@types/*'
catalog:
  '@types/qunit': '^2.19.12'
  '@types/node': '^20.17.10'
  'eslint': '^8.57.1'
  'publint': '^0.2.12'
  'qunit': '^2.23.1'
  'rollup': '^4.28.1'
  'typescript': '^5.7.2'
  'vite': '^6.0.3'
