packages:
  - 'bin'
  - 'build'
  - 'packages'
  - 'benchmark'
  - 'benchmark/benchmarks/krausest'
  - 'packages/@glimmer/*'
  - 'packages/@glimmer/*/test'
  - 'packages/@glimmer-workspace/*'
  - 'packages/@glimmer-workspace/*/test'
  - 'packages/@types/*'
catalog:
  eslint: ^8.57.1
  typescript: ^5.6.3
  vite: ^5.4.9
