packages:
  - 'bin'
  - 'build'
  - 'packages'
  - 'benchmark'
  - 'benchmark/benchmarks/krausest'
  - 'lib/local-linker'
  - 'packages/@glimmer/*'
  - 'packages/@glimmer/*/test'
  - 'packages/@glimmer-workspace/*'
  - 'packages/@glimmer-workspace/*/test'
  - 'packages/@types/*'
  - .yalc/*
  - .yalc/@*/*
