packages:
  - 'bin'
  - 'repo-metadata'
  - 'build'
  - 'packages'
  - 'packages/@glimmer/*'
  - 'packages/@glimmer/*/test'
  - 'packages/@glimmer-workspace/*'
  - 'packages/@glimmer-workspace/*/test'
  - 'packages/@types/*'
