// Generated by CoffeeScript 1.12.7

export function extendedTypeOf(obj) {
  var result;
  result = typeof obj;
  if (obj == null) {
    return 'null';
  } else if (result === 'object' && obj.constructor === Array) {
    return 'array';
  } else {
    return result;
  }
}
