import type {
  AppendOpcode,
  AttrSplatOpcode,
  BlockOpcode,
  CallLexicalOpcode,
  CallResolvedOpcode,
  CloseElementOpcode,
  CommentOpcode,
  ComponentAttrOpcode,
  ComponentOpcode,
  ConcatOpcode,
  CurryOpcode,
  DebuggerOpcode,
  DynamicArgOpcode,
  DynamicAttrOpcode,
  EachOpcode,
  FlushElementOpcode,
  GetDynamicVarOpcode,
  GetFreeAsComponentHeadOpcode,
  GetFreeAsComponentOrHelperHeadOpcode,
  GetFreeAsHelperHeadOpcode,
  GetFreeAsModifierHeadOpcode,
  GetLexicalSymbolOpcode,
  GetStrictKeywordOpcode,
  GetSymbolOpcode,
  HasBlockOpcode,
  HasBlockParamsOpcode,
  IfInlineOpcode,
  IfOpcode,
  InElementOpcode,
  InvokeComponentOpcode,
  LetOpcode,
  LogOpcode,
  ModifierOpcode,
  NotOpcode,
  OpenElementOpcode,
  OpenElementWithSplatOpcode,
  StaticArgOpcode,
  StaticAttrOpcode,
  StaticComponentAttrOpcode,
  StrictBlockOpcode,
  StrictModifierOpcode,
  TrustingAppendOpcode,
  TrustingComponentAttrOpcode,
  TrustingDynamicAttrOpcode,
  UndefinedOpcode,
  UnknownAppendOpcode,
  UnknownInvokeOpcode,
  UnknownTrustingAppendOpcode,
  WithDynamicVarsOpcode,
  YieldOpcode,
} from '@glimmer/interfaces';

export const opcodes = {
  Append: 1 satisfies AppendOpcode,
  UnknownAppend: 2 satisfies UnknownAppendOpcode,
  UnknownTrustingAppend: 3 satisfies UnknownTrustingAppendOpcode,
  TrustingAppend: 4 satisfies TrustingAppendOpcode,
  Comment: 5 satisfies CommentOpcode,
  Modifier: 6 satisfies ModifierOpcode,
  StrictModifier: 7 satisfies StrictModifierOpcode,
  Block: 8 satisfies BlockOpcode,
  StrictBlock: 9 satisfies StrictBlockOpcode,
  Component: 10 satisfies ComponentOpcode,
  OpenElement: 11 satisfies OpenElementOpcode,
  OpenElementWithSplat: 12 satisfies OpenElementWithSplatOpcode,
  FlushElement: 13 satisfies FlushElementOpcode,
  CloseElement: 14 satisfies CloseElementOpcode,
  StaticAttr: 15 satisfies StaticAttrOpcode,
  DynamicAttr: 16 satisfies DynamicAttrOpcode,
  ComponentAttr: 17 satisfies ComponentAttrOpcode,
  AttrSplat: 18 satisfies AttrSplatOpcode,
  Yield: 19 satisfies YieldOpcode,
  DynamicArg: 20 satisfies DynamicArgOpcode,
  StaticArg: 21 satisfies StaticArgOpcode,
  TrustingDynamicAttr: 22 satisfies TrustingDynamicAttrOpcode,
  TrustingComponentAttr: 23 satisfies TrustingComponentAttrOpcode,
  StaticComponentAttr: 24 satisfies StaticComponentAttrOpcode,
  Debugger: 26 satisfies DebuggerOpcode,
  Undefined: 27 satisfies UndefinedOpcode,
  CallResolved: 28 satisfies CallResolvedOpcode,
  CallLexical: 29 satisfies CallLexicalOpcode,
  UnknownInvoke: 30 satisfies UnknownInvokeOpcode,
  Concat: 31 satisfies ConcatOpcode,
  GetSymbol: 32 satisfies GetSymbolOpcode,
  GetLexicalSymbol: 33 satisfies GetLexicalSymbolOpcode,
  GetStrictKeyword: 34 satisfies GetStrictKeywordOpcode,
  GetFreeAsComponentOrHelperHead: 35 satisfies GetFreeAsComponentOrHelperHeadOpcode,
  GetFreeAsHelperHead: 37 satisfies GetFreeAsHelperHeadOpcode,
  GetFreeAsModifierHead: 38 satisfies GetFreeAsModifierHeadOpcode,
  GetFreeAsComponentHead: 39 satisfies GetFreeAsComponentHeadOpcode,
  InElement: 40 satisfies InElementOpcode,
  If: 41 satisfies IfOpcode,
  Each: 42 satisfies EachOpcode,
  Let: 44 satisfies LetOpcode,
  WithDynamicVars: 45 satisfies WithDynamicVarsOpcode,
  InvokeComponent: 46 satisfies InvokeComponentOpcode,
  HasBlock: 48 satisfies HasBlockOpcode,
  HasBlockParams: 49 satisfies HasBlockParamsOpcode,
  Curry: 50 satisfies CurryOpcode,
  Not: 51 satisfies NotOpcode,
  IfInline: 52 satisfies IfInlineOpcode,
  GetDynamicVar: 53 satisfies GetDynamicVarOpcode,
  Log: 54 satisfies LogOpcode,
} as const;
