import type {
  AppendBuiltinHelperOpcode,
  AppendLexicalOpcode,
  AppendOpcode,
  AppendResolvedHelperOpcode,
  AppendResolvedOpcode,
  AppendStaticOpcode,
  AppendTrustedHtmlOpcode,
  AttrSplatOpcode,
  CallLexicalOpcode,
  CallResolvedOpcode,
  CloseElementOpcode,
  CommentOpcode,
  ComponentAttrOpcode,
  ConcatOpcode,
  CurryOpcode,
  DebuggerOpcode,
  DynamicArgOpcode,
  DynamicAttrOpcode,
  DynamicBlockOpcode,
  EachOpcode,
  FlushElementOpcode,
  GetDynamicVarOpcode,
  GetLexicalSymbolOpcode,
  GetLocalSymbolOpcode,
  GetStrictKeywordOpcode,
  HasBlockOpcode,
  HasBlockParamsOpcode,
  IfInlineOpcode,
  IfOpcode,
  InElementOpcode,
  InvokeComponentKeywordOpcode,
  InvokeDynamicComponentOpcode,
  InvokeLexicalComponentOpcode,
  InvokeResolvedComponentOpcode,
  LetOpcode,
  LexicalBlockComponentOpcode,
  LexicalModifierOpcode,
  LogOpcode,
  NotOpcode,
  OpenElementOpcode,
  OpenElementWithSplatOpcode,
  ResolveAsComponentHeadOpcode,
  ResolveAsComponentOrHelperHeadOpcode,
  ResolveAsHelperHeadOpcode,
  ResolveAsModifierHeadOpcode,
  ResolvedBlockOpcode,
  ResolvedModifierOpcode,
  StaticArgOpcode,
  StaticAttrOpcode,
  StaticComponentAttrOpcode,
  StrictModifierOpcode,
  TrustingComponentAttrOpcode,
  TrustingDynamicAttrOpcode,
  UndefinedOpcode,
  UnknownAppendOpcode,
  UnknownInvokeOpcode,
  UnknownTrustingAppendOpcode,
  WithDynamicVarsOpcode,
  YieldOpcode,
} from '@glimmer/interfaces';

export const opcodes = {
  Append: 1 satisfies AppendOpcode,
  AppendStatic: 104 satisfies AppendStaticOpcode,
  AppendResolved: 100 satisfies AppendResolvedOpcode,
  AppendLexical: 103 satisfies AppendLexicalOpcode,
  AppendResolvedHelper: 101 satisfies AppendResolvedHelperOpcode,
  AppendBuiltinHelper: 102 satisfies AppendBuiltinHelperOpcode,
  UnknownAppend: 2 satisfies UnknownAppendOpcode,
  UnknownTrustingAppend: 3 satisfies UnknownTrustingAppendOpcode,

  LexicalBlockComponent: 9 satisfies LexicalBlockComponentOpcode,
  InvokeDynamicComponent: 58 satisfies InvokeDynamicComponentOpcode,
  InvokeComponentKeyword: 46 satisfies InvokeComponentKeywordOpcode,
  InvokeResolvedComponent: 47 satisfies InvokeResolvedComponentOpcode,
  InvokeLexicalComponent: 55 satisfies InvokeLexicalComponentOpcode,

  AppendTrustedHtml: 4 satisfies AppendTrustedHtmlOpcode,
  Comment: 5 satisfies CommentOpcode,
  LexicalModifier: 6 satisfies LexicalModifierOpcode,
  ResolvedModifier: 56 satisfies ResolvedModifierOpcode,
  StrictModifier: 7 satisfies StrictModifierOpcode,
  DynamicBlock: 57 satisfies DynamicBlockOpcode,
  ResolvedBlock: 8 satisfies ResolvedBlockOpcode,
  OpenElement: 11 satisfies OpenElementOpcode,
  OpenElementWithSplat: 12 satisfies OpenElementWithSplatOpcode,
  FlushElement: 13 satisfies FlushElementOpcode,
  CloseElement: 14 satisfies CloseElementOpcode,
  StaticAttr: 15 satisfies StaticAttrOpcode,
  DynamicAttr: 16 satisfies DynamicAttrOpcode,
  ComponentAttr: 17 satisfies ComponentAttrOpcode,
  AttrSplat: 18 satisfies AttrSplatOpcode,
  Yield: 19 satisfies YieldOpcode,
  DynamicArg: 20 satisfies DynamicArgOpcode,
  StaticArg: 21 satisfies StaticArgOpcode,
  TrustingDynamicAttr: 22 satisfies TrustingDynamicAttrOpcode,
  TrustingComponentAttr: 23 satisfies TrustingComponentAttrOpcode,
  StaticComponentAttr: 24 satisfies StaticComponentAttrOpcode,
  Debugger: 26 satisfies DebuggerOpcode,
  Undefined: 27 satisfies UndefinedOpcode,
  CallResolved: 28 satisfies CallResolvedOpcode,
  CallLexical: 29 satisfies CallLexicalOpcode,
  UnknownInvoke: 30 satisfies UnknownInvokeOpcode,
  Concat: 31 satisfies ConcatOpcode,
  GetLocalSymbol: 32 satisfies GetLocalSymbolOpcode,
  GetLexicalSymbol: 33 satisfies GetLexicalSymbolOpcode,
  GetStrictKeyword: 34 satisfies GetStrictKeywordOpcode,
  GetFreeAsComponentOrHelperHead: 35 satisfies ResolveAsComponentOrHelperHeadOpcode,
  GetFreeAsHelperHead: 37 satisfies ResolveAsHelperHeadOpcode,
  GetFreeAsModifierHead: 38 satisfies ResolveAsModifierHeadOpcode,
  GetFreeAsComponentHead: 39 satisfies ResolveAsComponentHeadOpcode,
  InElement: 40 satisfies InElementOpcode,
  If: 41 satisfies IfOpcode,
  Each: 42 satisfies EachOpcode,
  Let: 44 satisfies LetOpcode,
  WithDynamicVars: 45 satisfies WithDynamicVarsOpcode,
  HasBlock: 48 satisfies HasBlockOpcode,
  HasBlockParams: 49 satisfies HasBlockParamsOpcode,
  Curry: 50 satisfies CurryOpcode,
  Not: 51 satisfies NotOpcode,
  IfInline: 52 satisfies IfInlineOpcode,
  GetDynamicVar: 53 satisfies GetDynamicVarOpcode,
  Log: 54 satisfies LogOpcode,
} as const;
