export { opcodeMetadata } from './lib/opcode-metadata';
export {
  OPERAND_TYPES,
  type OperandType,
  type Operand,
  type OperandList,
  type NormalizedMetadata,
  type Stack,
  type RawOperandMetadata,
  type OperandName,
  type RawOperandFormat,
  normalize,
  type NormalizedOpcodes,
  normalizeAll,
  normalizeParsed,
  buildEnum,
  strip,
  META_KIND,
  buildSingleMeta,
  buildMetas,
} from './lib/metadata';
