name: PerformanceCheck

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches: [master]


env:
  TEMP_DIR: ''

jobs:
  master-krausest-comparison:
    name: Glimmer Krausest Benchmark
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hi'
